import { afterEach, beforeEach, describe, it } from "node:test";
import assert from "node:assert/strict";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  buildRtkAliasesScript,
  isRtkEnabled,
  omxRuntimeConfigPath,
  readRtkEnabledSetting,
  resolveRtkBashEnv,
  resolveRtkExecutable,
  rtkAliasesPath,
  syncRtkRuntimeConfig,
  writeRtkAliasesFile,
} from "../index.js";

describe("rtk integration helpers", () => {
  let tempDir: string;
  let originalHome: string | undefined;
  let originalCodexHome: string | undefined;
  let originalPath: string | undefined;

  beforeEach(async () => {
    tempDir = await mkdtemp(join(tmpdir(), "omx-rtk-"));
    originalHome = process.env.HOME;
    originalCodexHome = process.env.CODEX_HOME;
    originalPath = process.env.PATH;
    process.env.HOME = tempDir;
    process.env.CODEX_HOME = join(tempDir, ".codex");
    process.env.PATH = "";
    await mkdir(process.env.CODEX_HOME, { recursive: true });
  });

  afterEach(async () => {
    if (typeof originalHome === "string") process.env.HOME = originalHome;
    else delete process.env.HOME;
    if (typeof originalCodexHome === "string") process.env.CODEX_HOME = originalCodexHome;
    else delete process.env.CODEX_HOME;
    if (typeof originalPath === "string") process.env.PATH = originalPath;
    else delete process.env.PATH;
    await rm(tempDir, { recursive: true, force: true });
  });

  async function writeRuntimeConfig(config: Record<string, unknown>): Promise<void> {
    await writeFile(omxRuntimeConfigPath(), JSON.stringify(config, null, 2));
  }

  async function createFakeRtkBinary(dirName = "bin"): Promise<string> {
    const binDir = join(tempDir, dirName);
    const binaryPath = join(binDir, "rtk");
    await mkdir(binDir, { recursive: true });
    await writeFile(
      binaryPath,
      "#!/bin/sh\nif [ \"$1\" = \"--version\" ]; then echo 'rtk 0.27.1'; exit 0; fi\necho ok\n",
    );
    await chmod(binaryPath, 0o755);
    process.env.PATH = `${binDir}`;
    return binaryPath;
  }

  it("reads rtk.enabled from .omx-config.json", async () => {
    await writeRuntimeConfig({ rtk: { enabled: false } });
    assert.equal(readRtkEnabledSetting(), false);
  });

  it("defaults rtk.enabled to installed state when config is absent", async () => {
    assert.equal(isRtkEnabled(), false);
    await createFakeRtkBinary();
    assert.equal(isRtkEnabled(), true);
  });

  it("respects explicit opt-out even when rtk is installed", async () => {
    await createFakeRtkBinary();
    await writeRuntimeConfig({ rtk: { enabled: false } });
    assert.equal(isRtkEnabled(), false);
  });

  it("writes alias file for supported commands", async () => {
    const binaryPath = await createFakeRtkBinary();
    const changed = await writeRtkAliasesFile(binaryPath);
    assert.equal(changed, true);
    const content = await readFile(rtkAliasesPath(), "utf-8");
    assert.match(content, /alias git='"\$RTK_BIN" git'/);
    assert.match(content, /alias cat='"\$RTK_BIN" read'/);
    assert.match(content, /alias rg='"\$RTK_BIN" grep'/);
    assert.match(content, new RegExp(`RTK_BIN="${binaryPath.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"`));
  });

  it("seeds rtk.enabled into runtime config when missing and preserves other keys", async () => {
    await writeRuntimeConfig({ notifications: { enabled: true } });
    const changed = await syncRtkRuntimeConfig(process.env.CODEX_HOME!, true);
    assert.equal(changed, true);
    const raw = JSON.parse(await readFile(omxRuntimeConfigPath(), "utf-8")) as Record<string, any>;
    assert.equal(raw.notifications.enabled, true);
    assert.equal(raw.rtk.enabled, true);
  });

  it("does not override explicit rtk.enabled when already present", async () => {
    await writeRuntimeConfig({ rtk: { enabled: false } });
    const changed = await syncRtkRuntimeConfig(process.env.CODEX_HOME!, true);
    assert.equal(changed, false);
    assert.equal(readRtkEnabledSetting(), false);
  });

  it("resolves BASH_ENV only when enabled and aliases exist", async () => {
    const binaryPath = await createFakeRtkBinary();
    assert.equal(resolveRtkExecutable(), binaryPath);
    assert.equal(resolveRtkBashEnv(), undefined);
    await writeRtkAliasesFile(binaryPath);
    assert.equal(resolveRtkBashEnv(), rtkAliasesPath());
    await writeRuntimeConfig({ rtk: { enabled: false } });
    assert.equal(resolveRtkBashEnv(), undefined);
  });

  it("builds deterministic alias script content", async () => {
    const binaryPath = await createFakeRtkBinary();
    const script = buildRtkAliasesScript(binaryPath);
    assert.match(script, /^# Generated by omx setup/m);
    assert.match(script, /alias docker='"\$RTK_BIN" docker'/);
    assert.match(script, /alias kubectl='"\$RTK_BIN" kubectl'/);
  });
});
