import { spawnSync } from "child_process";
import { existsSync, readFileSync } from "fs";
import { mkdir, readFile, writeFile } from "fs/promises";
import { homedir } from "os";
import { delimiter, join } from "path";
import { codexHome } from "../utils/paths.js";

export interface RtkConfigBlock {
  enabled?: boolean;
}

interface OmxRuntimeConfig {
  [key: string]: unknown;
  rtk?: RtkConfigBlock;
}

export interface EnsureRtkOptions {
  dryRun?: boolean;
  verbose?: boolean;
}

export interface EnsureRtkResult {
  aliasesPath: string;
  aliasFileWritten: boolean;
  executablePath?: string;
  installed: boolean;
  installMethod: "existing" | "cargo" | "brew" | "dry-run" | "unavailable";
}

export const RTK_ALIAS_DEFINITIONS = [
  { name: "aws", target: "aws" },
  { name: "biome", target: "lint" },
  { name: "cargo", target: "cargo" },
  { name: "cat", target: "read" },
  { name: "curl", target: "curl" },
  { name: "diff", target: "diff" },
  { name: "docker", target: "docker" },
  { name: "eslint", target: "lint" },
  { name: "find", target: "find" },
  { name: "gh", target: "gh" },
  { name: "git", target: "git" },
  { name: "go", target: "go" },
  { name: "golangci-lint", target: "golangci-lint" },
  { name: "grep", target: "grep" },
  { name: "kubectl", target: "kubectl" },
  { name: "ls", target: "ls" },
  { name: "mypy", target: "mypy" },
  { name: "next", target: "next" },
  { name: "npm", target: "npm" },
  { name: "npx", target: "npx" },
  { name: "pip", target: "pip" },
  { name: "playwright", target: "playwright" },
  { name: "pnpm", target: "pnpm" },
  { name: "prettier", target: "prettier" },
  { name: "prisma", target: "prisma" },
  { name: "psql", target: "psql" },
  { name: "pytest", target: "pytest" },
  { name: "rg", target: "grep" },
  { name: "ruff", target: "ruff" },
  { name: "tree", target: "tree" },
  { name: "tsc", target: "tsc" },
  { name: "vitest", target: "vitest" },
  { name: "wc", target: "wc" },
  { name: "wget", target: "wget" },
] as const;

const RTK_CONFIG_FILE = ".omx-config.json";

export function omxRuntimeConfigPath(codexHomeOverride?: string): string {
  return join(codexHomeOverride || codexHome(), RTK_CONFIG_FILE);
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readOmxRuntimeConfig(
  codexHomeOverride?: string,
): OmxRuntimeConfig | null {
  const configPath = omxRuntimeConfigPath(codexHomeOverride);
  if (!existsSync(configPath)) return null;
  try {
    const raw = JSON.parse(readFileSync(configPath, "utf-8")) as unknown;
    return isPlainObject(raw) ? (raw as OmxRuntimeConfig) : null;
  } catch {
    return null;
  }
}

export function readRtkEnabledSetting(
  codexHomeOverride?: string,
): boolean | undefined {
  const config = readOmxRuntimeConfig(codexHomeOverride);
  const enabled = config?.rtk?.enabled;
  return typeof enabled === "boolean" ? enabled : undefined;
}

function rtkBinaryName(): string {
  return process.platform === "win32" ? "rtk.exe" : "rtk";
}

function resolveSearchDirs(env: NodeJS.ProcessEnv = process.env): string[] {
  const pathDirs = (env.PATH || "")
    .split(delimiter)
    .map((entry) => entry.trim())
    .filter(Boolean);
  return Array.from(
    new Set([
      ...pathDirs,
      join(homedir(), ".cargo", "bin"),
      join(homedir(), ".local", "bin"),
      "/opt/homebrew/bin",
      "/usr/local/bin",
      "/usr/bin",
    ]),
  );
}

function isWorkingRtkBinary(
  candidate: string,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  const result = spawnSync(candidate, ["--version"], {
    encoding: "utf-8",
    env,
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.error) return false;
  return result.status === 0;
}

export function resolveRtkExecutable(
  env: NodeJS.ProcessEnv = process.env,
): string | undefined {
  const binaryName = rtkBinaryName();
  for (const dir of resolveSearchDirs(env)) {
    const candidate = join(dir, binaryName);
    if (!existsSync(candidate)) continue;
    if (isWorkingRtkBinary(candidate, env)) return candidate;
  }
  if (isWorkingRtkBinary(binaryName, env)) return binaryName;
  return undefined;
}

export function isRtkInstalled(env: NodeJS.ProcessEnv = process.env): boolean {
  return typeof resolveRtkExecutable(env) === "string";
}

export function isRtkEnabled(
  codexHomeOverride?: string,
  env: NodeJS.ProcessEnv = process.env,
): boolean {
  const explicit = readRtkEnabledSetting(codexHomeOverride);
  return explicit ?? isRtkInstalled(env);
}

export function rtkAliasesPath(): string {
  return join(homedir(), ".omx", "rtk-aliases.sh");
}

function escapeDoubleQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function buildRtkAliasesScript(executablePath: string): string {
  return [
    "#!/usr/bin/env bash",
    "# Generated by omx setup. Session-scoped RTK wrappers for Codex shells.",
    'if [ -n "${BASH_VERSION:-}" ]; then',
    "  shopt -s expand_aliases",
    "fi",
    "",
    `RTK_BIN="${escapeDoubleQuoted(executablePath)}"`,
    'if ! command -v "$RTK_BIN" >/dev/null 2>&1; then',
    "  return 0 2>/dev/null || true",
    "fi",
    "",
    ...RTK_ALIAS_DEFINITIONS.map(
      ({ name, target }) => `alias ${name}='"$RTK_BIN" ${target}'`,
    ),
    "",
  ].join("\n");
}

export async function writeRtkAliasesFile(
  executablePath: string,
  options: EnsureRtkOptions = {},
): Promise<boolean> {
  const aliasesPath = rtkAliasesPath();
  const content = buildRtkAliasesScript(executablePath);
  const current = existsSync(aliasesPath)
    ? await readFile(aliasesPath, "utf-8")
    : undefined;
  if (current === content) return false;

  if (!options.dryRun) {
    await mkdir(join(homedir(), ".omx"), { recursive: true });
    await writeFile(aliasesPath, content);
  }
  return true;
}

function runInstallAttempt(
  command: string,
  args: string[],
  options: Pick<EnsureRtkOptions, "verbose"> = {},
): boolean {
  const result = spawnSync(command, args, {
    encoding: "utf-8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (options.verbose && result.stdout.trim()) {
    console.log(result.stdout.trim());
  }
  if (options.verbose && result.stderr.trim()) {
    console.error(result.stderr.trim());
  }
  if (result.error) return false;
  return result.status === 0;
}

export async function ensureRtkInstalledAndAliases(
  options: EnsureRtkOptions = {},
): Promise<EnsureRtkResult> {
  const aliasesPath = rtkAliasesPath();
  const existingExecutable = resolveRtkExecutable();
  if (existingExecutable) {
    const aliasFileWritten = await writeRtkAliasesFile(existingExecutable, options);
    return {
      aliasesPath,
      aliasFileWritten,
      executablePath: existingExecutable,
      installed: true,
      installMethod: "existing",
    };
  }

  if (options.dryRun) {
    return {
      aliasesPath,
      aliasFileWritten: false,
      installed: false,
      installMethod: "dry-run",
    };
  }

  let installMethod: EnsureRtkResult["installMethod"] = "unavailable";
  if (
    runInstallAttempt("cargo", ["install", "--git", "https://github.com/rtk-ai/rtk"], options)
  ) {
    installMethod = "cargo";
  } else if (runInstallAttempt("brew", ["install", "rtk"], options)) {
    installMethod = "brew";
  }

  const executablePath = resolveRtkExecutable();
  if (!executablePath) {
    return {
      aliasesPath,
      aliasFileWritten: false,
      installed: false,
      installMethod,
    };
  }

  const aliasFileWritten = await writeRtkAliasesFile(executablePath, options);
  return {
    aliasesPath,
    aliasFileWritten,
    executablePath,
    installed: true,
    installMethod,
  };
}

export async function syncRtkRuntimeConfig(
  codexHomeDir: string,
  defaultEnabled: boolean,
  options: EnsureRtkOptions = {},
): Promise<boolean> {
  const configPath = omxRuntimeConfigPath(codexHomeDir);
  const raw = existsSync(configPath) ? await readFile(configPath, "utf-8") : "";
  let parsed: Record<string, unknown> = {};
  if (raw.trim() !== "") {
    try {
      const next = JSON.parse(raw) as unknown;
      if (isPlainObject(next)) parsed = next;
    } catch {
      parsed = {};
    }
  }

  const currentBlock = isPlainObject(parsed.rtk) ? parsed.rtk : {};
  if (typeof currentBlock.enabled === "boolean") return false;

  const next = {
    ...parsed,
    rtk: {
      ...currentBlock,
      enabled: defaultEnabled,
    },
  };
  const content = JSON.stringify(next, null, 2) + "\n";
  if (!options.dryRun) {
    await mkdir(codexHomeDir, { recursive: true });
    await writeFile(configPath, content);
  }
  return true;
}

export function resolveRtkBashEnv(
  codexHomeOverride?: string,
  env: NodeJS.ProcessEnv = process.env,
): string | undefined {
  if (!isRtkEnabled(codexHomeOverride, env)) return undefined;
  const aliasesPath = rtkAliasesPath();
  if (!existsSync(aliasesPath)) return undefined;
  return aliasesPath;
}

export function withRtkBashEnv(
  baseEnv: NodeJS.ProcessEnv,
  codexHomeOverride?: string,
): NodeJS.ProcessEnv {
  const bashEnv = resolveRtkBashEnv(codexHomeOverride, baseEnv);
  if (!bashEnv) return baseEnv;
  return { ...baseEnv, BASH_ENV: bashEnv };
}
